### ISSUE TITLE
[Bug]: Navigation broken after login

### ISSUE THREAD

**Issue by SGiumelli** [SwisseSportsFederation/esports-hub#173]
### What happened?

After login, the navigation on the page https://hub.sesf.ch/admin/user/account is broken. I am always sent back to https://hub.sesf.ch/admin/user/account when clicking on "games" and all the other items.

### What browsers are you seeing the problem on?

Chrome

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
@SGiumelli this is a feature not a bug. (But yeah we should add more information why the user is stuck there.) We need to have the required fields set before the user can use his account.
That's why the user is always redirected. I could also hide the navbar if the user is not fully filled out yet.

**Comment by zischler** [comment]
issue for optimization: #183
