### ISSUE TITLE
[Bug]: No End Date for Team Entry possible

### ISSUE THREAD

**Issue by thenzler** [SwisseSportsFederation/esports-hub#184]
### Contact Details

th.henzler@gmail.com

### What happened?

When Entrying a new Team in your Account , if you dont enter an End date  you get an unexpected Server Error 
![image](https://github.com/user-attachments/assets/79f88388-6c9f-444d-8250-b1e44e0a2e48)

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
done
