### ISSUE TITLE
[Bug]: Uploaded Profile Picture is always Swiss Ghosts Logo

### ISSUE THREAD

**Issue by sioser** [SwisseSportsFederation/esports-hub#185]
### Contact Details

losersilvan@gmail.com

### What happened?

No matter what picture you upload as a profile picture, it always changes to the swiss ghosts logo after a few seconds.

### What browsers are you seeing the problem on?

Chrome

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
Can you please test again @sioser ?
I think it might just be a caching bug.

**Comment by sioser** [comment]
@zischler Heard it was resolved last week already but tested myself just now and it works as intended!
