### ISSUE TITLE
[Bug]: Filter options in overview not working

### ISSUE THREAD

**Issue by IrusVirus** [SwisseSportsFederation/esports-hub#202]
### Contact Details

irusvirus@msn.com

### What happened?

No matter which filter is used on the main page, it is not filtered 100% as it should be.
Here is an example with Fortnite:
![grafik](https://github.com/user-attachments/assets/fda09269-ac19-491b-81e5-703ca857b751)

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
I love it. I readded a bug that I fixed months ago. 😆 
Will look at it soonish
