### ISSUE TITLE
Error while applying for team

### ISSUE THREAD

**Issue by IrusVirus** [SwisseSportsFederation/esports-hub#203]
### What happened?

Error message on user side:
![IMG_2889](https://github.com/user-attachments/assets/7294d4df-3e7e-45f7-ac2a-d423ed372a54)

But the apply works:
![IMG_2604](https://github.com/user-attachments/assets/2271b095-7e95-4689-bd56-185d538ffdbe)

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
Will be fixed on next deployment. This problem occurred when a person applied for a team more than once.
