### ISSUE TITLE
[Idea]: Profile button in header menu

### ISSUE THREAD

**Issue by IrusVirus** [SwisseSportsFederation/esports-hub#205]
### Contact Details

irusvirus@msn.com

### Idea

a “Profile” button in the header menu so that you can go directly to your profile.
![grafik](https://github.com/user-attachments/assets/518b2233-5759-4aea-b515-28e668baf4f1)
e.g. link to https://hub.sesf.ch/detail/user/IrusVirus

### Data Policy

- [X] I agree to the privacy policy of SESF

**Comment by zischler** [comment]
Cool idea, will have a look to it when the other bugs are fixed.
